services:
  app:
    build:
      context: .
      dockerfile: src/backend/dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - src/backend/.env
    depends_on:
      - db
    
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    ports:
      - "80:80"
    depends_on:
      - app
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hexlet
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
