[project]
name = "hexlet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.22.1",
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "fastapi>=0.136.0",
    "greenlet>=3.4.0",
    "loguru>=0.7.3",
    "passlib[bcrypt]>=1.7.4",
    "pydantic-settings>=2.13.1",
    "pydantic[email]>=2.13.2",
    "pyjwt>=2.12.1",
    "sqlalchemy2-stubs>=0.0.2a38",
    "sqlalchemy[mypy]>=2.0.49",
    "uvicorn>=0.44.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.12",
]


[tool.ruff]
fix = true
line-length = 88
exclude = [
    ".git", 
    "__pycache__", 
    ".venv", 
    "build", 
    "dist"
]

[tool.ruff.lint]
# Включенные правила
select = ["E", "F", "I", "UP", "N", "B", "C4", "RUF"]

# Правила, которые нужно игнорировать
ignore = ["E501", "B008", "B904", "RUF012"]

[tool.ruff.lint.per-file-ignores]
"alembic/*.py" = ["E402"] # Игнорировать порядок импортов в папке alembic
"src/backend/models/*.py" = ["F821"] # Что бы не ругался на импорт классов таблиц
"**/env.py" = ["F401"]

# Настройка isort
[tool.ruff.lint.isort]
known-first-party = ["src" ,"hexlet"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"
