FROM python:3.11-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV UV_SYSTEM_PYTHON=1 \
    UV_COMPILE_BYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN uv pip install --no-cache -r pyproject.toml

COPY . .

CMD ["uvicorn", "src.backend.api_v1.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
