"""create users

Revision ID: 0cc3475a2fa1
Revises: 
Create Date: 2026-04-20 13:34:55.988804

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '0cc3475a2fa1'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
