"""del uniq

Revision ID: 0f8c903c2a30
Revises: 5c1597e4b33a
Create Date: 2026-05-02 14:36:48.238549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8c903c2a30'
down_revision: Union[str, Sequence[str], None] = '5c1597e4b33a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lesson_information_key'), 'lesson', type_='unique')
    op.drop_constraint(op.f('lesson_title_key'), 'lesson', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('lesson_title_key'), 'lesson', ['title'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('lesson_information_key'), 'lesson', ['information'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
