"""del order

Revision ID: 36a7071c236a
Revises: ad8e84a1bb15
Create Date: 2026-05-01 12:28:09.358159

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '36a7071c236a'
down_revision: str | Sequence[str] | None = 'ad8e84a1bb15'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# В файле миграции (xxxx_change_curr_answer_type.py)
def upgrade():
    op.alter_column(
        'test',
        'curr_answer',
        existing_type=sa.VARCHAR(),
        type_=postgresql.JSONB(),
        postgresql_using='curr_answer::jsonb',  # Добавьте эту строку
        existing_nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
