"""initial

Revision ID: 5b6f5d6b6e4d
Revises: 87d008f043d8
Create Date: 2026-04-26 18:22:12.564696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6f5d6b6e4d'
down_revision: Union[str, Sequence[str], None] = '87d008f043d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unique_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_unique_user_id_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['unique_id'])
    op.drop_column('users', 'unique_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unique_user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_unique_user_id_key'), 'users', ['unique_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'email')
    op.drop_column('users', 'password')
    op.drop_column('users', 'unique_id')
    # ### end Alembic commands ###
