"""del order

Revision ID: 5c1597e4b33a
Revises: 36a7071c236a
Create Date: 2026-05-01 15:13:58.646639

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5c1597e4b33a'
down_revision: str | Sequence[str] | None = '36a7071c236a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade():
    op.alter_column(
        'test',
        'curr_answer',
        existing_type=sa.VARCHAR(),
        type_=postgresql.JSONB(),
        postgresql_using='curr_answer::jsonb',  # Добавьте эту строку
        existing_nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'test',
        'curr_answer',
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
