"""user database

Revision ID: 87d008f043d8
Revises: 9e20425d4a2d
Create Date: 2026-04-21 17:50:17.891123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d008f043d8'
down_revision: Union[str, Sequence[str], None] = '9e20425d4a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unique_user_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('level', sa.Integer(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('xp', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('energy', sa.Integer(), server_default='10', nullable=False))
    op.add_column('users', sa.Column('floor', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('floor_level', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.create_unique_constraint(None, 'users', ['unique_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'floor_level')
    op.drop_column('users', 'floor')
    op.drop_column('users', 'energy')
    op.drop_column('users', 'xp')
    op.drop_column('users', 'level')
    op.drop_column('users', 'unique_user_id')
    # ### end Alembic commands ###
