"""create lesson

Revision ID: 8c6e6f9c25a4
Revises: c83f5aa1cc54
Create Date: 2026-04-27 09:36:57.325533

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8c6e6f9c25a4'
down_revision: str | Sequence[str] | None = 'c83f5aa1cc54'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('information', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('information'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_lesson_id'), 'lesson', ['id'], unique=False)
    op.create_table('Test',
    sa.Column('for_lesson_id', sa.Integer(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('curr_answer', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['for_lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Test_for_lesson_id'), 'Test', ['for_lesson_id'], unique=False)
    op.create_index(op.f('ix_Test_id'), 'Test', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Test_id'), table_name='Test')
    op.drop_index(op.f('ix_Test_for_lesson_id'), table_name='Test')
    op.drop_table('Test')
    op.drop_index(op.f('ix_lesson_id'), table_name='lesson')
    op.drop_table('lesson')
    # ### end Alembic commands ###
