"""create users

Revision ID: a1285cdc69a8
Revises: 0cc3475a2fa1
Create Date: 2026-04-20 13:37:33.358396

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'a1285cdc69a8'
down_revision: str | Sequence[str] | None = '0cc3475a2fa1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
