"""create lesson db

Revision ID: c83f5aa1cc54
Revises: 5b6f5d6b6e4d
Create Date: 2026-04-26 22:01:15.312782

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c83f5aa1cc54'
down_revision: str | Sequence[str] | None = '5b6f5d6b6e4d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
